var connectionDetails = [
{connectionId:'con1' , connection_name:'The Testaments: The Sequel to The Handmaid\'s Tale' ,connection_category:'Book Club',details:'More than fifteen years after the events of The Handmaid\'s Tale, the theocratic regime of the Republic of Gilead maintains its grip on power, but there are signs it is beginning to rot from within. At this crucial moment, the lives of three radically different women converge, with potentially explosive results. Two have grown up as part of the first generation to come of age in the new order. The testimonies of these two young women are joined by a third: Aunt Lydia.  Her complex past and uncertain future unfold in surprising and pivotal ways. With The Testaments, Margaret Atwood opens up the innermost workings of Gilead, as each woman is forced to come to terms with who she is, and how far she will go for what she believes.'  ,dateAndTime:'Oct 7th 4.30 AM',hostedBy:'Margaret Atwood', image:'../assets/images/conImages/con1.jpg'},
{connectionId:'con2' , connection_name:'Daisy Jones & The Six: A Novel' ,connection_category:'Book Club',details:'Everyone knows DAISY JONES & THE SIX, but nobody knows the reason behind their split at the absolute height of their popularity . . . until now. Daisy is a girl coming of age in L.A. in the late sixties, sneaking into clubs on the Sunset Strip, sleeping with rock stars, and dreaming of singing at the Whisky a Go Go. The sex and drugs are thrilling, but it’s the rock ’n’ roll she loves most. By the time she’s twenty, her voice is getting noticed, and she has the kind of heedless beauty that makes people do crazy things. Also getting noticed is The Six, a band led by the brooding Billy Dunne. On the eve of their first tour, his girlfriend Camila finds out she’s pregnant, and with the pressure of impending fatherhood and fame, Billy goes a little wild on the road.  Daisy and Billy cross paths when a producer realizes that the key to supercharged success is to put the two together. What happens next will become the stuff of legend.  The making of that legend is chronicled in this riveting and unforgettable novel, written as an oral history of one of the biggest bands of the seventies. Taylor Jenkins Reid is a talented writer who takes her work to a new level with Daisy Jones & The Six, brilliantly capturing a place and time in an utterly distinctive voice.'  ,dateAndTime:'Oct 15th 5.30 AM',hostedBy:'Taylor Jenkins Reid', image:'../assets/images/conImages/con2.jpg'},
{connectionId:'con3' , connection_name:'The Last Thing You Surrender: A Novel of World War II' ,connection_category:'Book Club',details:'Pulitzer-winning journalist and bestselling novelist (Freeman) Leonard Pitts, Jr.\'s new historical page-turner is a great American tale of race and war, following three characters from the Jim Crow South as they face the enormous changes World War II triggers in the United States. An affluent white marine survives Pearl Harbor at the cost of a black messman\'s life only to be sent, wracked with guilt, to the Pacific and taken prisoner by the Japanese . . . a young black woman, widowed by the same events at Pearl, finds unexpected opportunity and a dangerous friendship in a segregated Alabama shipyard feeding the war . . . a black man, who as a child saw his parents brutally lynched, is conscripted to fight Nazis for a country he despises and discovers a new kind of patriotism in the all-black 761st Tank Battalion. Set against a backdrop of violent racial conflict on both the front lines and the home front, The Last Thing You Surrender explores the powerful moral struggles of individuals from a divided nation. What does it take to change someone\'s mind about race? What does it take for a country and a people to move forward, transformed?'  ,dateAndTime:'Oct 25th 6.30 AM',hostedBy:'Leonard Pitts, Jr.', image:'../assets/images/conImages/con3.jpg'},
{connectionId:'con4' , connection_name:'WNBA presents a Book Drive for ourBRIDGE' ,connection_category:'Events',details:'Both WNBA and ourBridge will have representatives at table instore to promote, accept donations, as well as educate folks on each organization. Please read below about ourBridge and consider donating to the book drive! ourBRIDGE for KIDS offers after school and summer programs to primarily refugee and newly arrived immigrant students. Each year, we welcome students who represent over twenty different cultures. All of our students speak at least one language other than English, some of them can speak four or more! ourBRIDGE for KIDS, at its core, attends to the academic and socio-emotional needs of our children and their families. We believe that a program based on our core values of LERD (Love, Education, Respect, and Diversity) will support students as they adjust to their new home after resettlement. We also believe that our curriculum must be shaped with our community in mind. Using research-based practices, ourBRIDGE has designed a curriculum framework that layers our four priorities: (1) English language acquisition (ESL/ELL), (2) STEAM, (3) culturally responsive, and (4) experiential. A ourBRIDGE, students receive homework help, participate in hands-on STEAM (Science, Technology, Engineering , Arts and Math) projects, and engage in a culturally relevant curriculum that emphasizes experiential learning. We provide one-on-one daily English literacy tutoring in order to accelerate the students’ acquisition of the English language. ourBRIDGE for KIDS aims to close the communication gap between school, teachers and families through the coordination of home visits, translation of school documents, and the organization of literacy nights and cultural events for parents at our center. When needed, we also provide parents transportation and translation support at teacher conferences and serve as the liaison between parents and schools.'  ,dateAndTime:'Sunday, February 23, 2020 - 1:00pm to 3:00pm',hostedBy:'ParkRoadBooks ', image:'../assets/images/conImages/con4.PNG'},
{connectionId:'con5' , connection_name:'Dr. Tracey Benson presents Unconscious Bias in Schools' ,connection_category:'Events',details:'According to Benson, regardless of the amount of effort, time, and resources educators put into improving the academic achievement of students of color, if unconscious racial bias is overlooked, improvement efforts may never achieve their highest potential. His newly released book, Unconscious Bias in Schools, provides educators with an essential roadmap for addressing these issues directly. The book draws on the literature on change management, leadership, critical race theory, and racial identity development, as well as the growing research on unconscious bias in a variety of fields, to provide guidance for creating the conditions necessary to do this work—awareness, trust, and a learner’s stance. It shows how raising awareness about unconscious bias can help shift conversations among educators to a more productive, collegial approach that has the potential to disrupt the patterns of perception that perpetuate racism and institutional injustice.'  ,dateAndTime:'Monday, February 24, 2020 - 7:00pm to 8:30pm',hostedBy:'Dr. Tracey Benson', image:'../assets/images/conImages/con5.PNG'},
{connectionId:'con6' , connection_name:'Jen Guberman presents EOS Dawn Series' ,connection_category:'Events',details:'Immerse yourself in the dystopian world of the Eos Dawn Series, a trilogy by Jen Guberman. In a post-war California, survivors rebuilt cities. With the population lower than ever, citizens had to resort to exiling criminals. Instead of casting them into a desert wasteland, they sent criminals off to ruined towns based on their crimes. When a young thief is exiled to Avid, a town full of thieves, she learns that the bad guys aren\'t always who they seem. '  ,dateAndTime:'Saturday, February 22, 2020 - 11:00am to 1:00pm',hostedBy:'Jen Guberman', image:'../assets/images/conImages/con6.PNG'},
{connectionId:'con6' , connection_name:'Jen Guberman presents EOS Dawn Series' ,connection_category:'Event Books',details:'Immerse yourself in the e Eos Dawn Series, a trilogy by Jen Guberman. In a post-war California, survivors rebuilt cities. With the population lower than ever, citizens had to resort to exiling criminals. Instead of casting them into a desert wasteland, they sent criminals off to ruined towns based on their crimes. When a young thief is exiled to Avid, a town full of thieves, she learns that the bad guys aren\'t always who they seem. '  ,dateAndTime:'Saturday, February 22, 2020 - 11:00am to 1:00pm',hostedBy:'Jen Guberman', image:'../assets/images/conImages/con6.PNG'}];

var savedConnections = [
  {connectionId:'con3' , connection_name:'The Last Thing You Surrender: A Novel of World War II' ,connection_category:'Book Club',details:'Pulitzer-winning journalist and bestselling novelist (Freeman) Leonard Pitts, Jr.\'s new historical page-turner is a great American tale of race and war, following three characters from the Jim Crow South as they face the enormous changes World War II triggers in the United States. An affluent white marine survives Pearl Harbor at the cost of a black messman\'s life only to be sent, wracked with guilt, to the Pacific and taken prisoner by the Japanese . . . a young black woman, widowed by the same events at Pearl, finds unexpected opportunity and a dangerous friendship in a segregated Alabama shipyard feeding the war . . . a black man, who as a child saw his parents brutally lynched, is conscripted to fight Nazis for a country he despises and discovers a new kind of patriotism in the all-black 761st Tank Battalion. Set against a backdrop of violent racial conflict on both the front lines and the home front, The Last Thing You Surrender explores the powerful moral struggles of individuals from a divided nation. What does it take to change someone\'s mind about race? What does it take for a country and a people to move forward, transformed?'  ,dateAndTime:'Oct 25th 6.30 AM',hostedBy:'Leonard Pitts, Jr.', image:'../assets/images/conImages/con3.jpg'},
  {connectionId:'con4' , connection_name:'WNBA presents a Book Drive for ourBRIDGE' ,connection_category:'Events',details:'Both WNBA and ourBridge will have representatives at table instore to promote, accept donations, as well as educate folks on each organization. Please read below about ourBridge and consider donating to the book drive! ourBRIDGE for KIDS offers after school and summer programs to primarily refugee and newly arrived immigrant students. Each year, we welcome students who represent over twenty different cultures. All of our students speak at least one language other than English, some of them can speak four or more! ourBRIDGE for KIDS, at its core, attends to the academic and socio-emotional needs of our children and their families. We believe that a program based on our core values of LERD (Love, Education, Respect, and Diversity) will support students as they adjust to their new home after resettlement. We also believe that our curriculum must be shaped with our community in mind. Using research-based practices, ourBRIDGE has designed a curriculum framework that layers our four priorities: (1) English language acquisition (ESL/ELL), (2) STEAM, (3) culturally responsive, and (4) experiential. A ourBRIDGE, students receive homework help, participate in hands-on STEAM (Science, Technology, Engineering , Arts and Math) projects, and engage in a culturally relevant curriculum that emphasizes experiential learning. We provide one-on-one daily English literacy tutoring in order to accelerate the students’ acquisition of the English language. ourBRIDGE for KIDS aims to close the communication gap between school, teachers and families through the coordination of home visits, translation of school documents, and the organization of literacy nights and cultural events for parents at our center. When needed, we also provide parents transportation and translation support at teacher conferences and serve as the liaison between parents and schools.'  ,dateAndTime:'Sunday, February 23, 2020 - 1:00pm to 3:00pm',hostedBy:'ParkRoadBooks ', image:'../assets/images/conImages/con4.PNG'},
  {connectionId:'con6' , connection_name:'Jen Guberman presents EOS Dawn Series' ,connection_category:'Event Books',details:'Immerse yourself in the e Eos Dawn Series, a trilogy by Jen Guberman. In a post-war California, survivors rebuilt cities. With the population lower than ever, citizens had to resort to exiling criminals. Instead of casting them into a desert wasteland, they sent criminals off to ruined towns based on their crimes. When a young thief is exiled to Avid, a town full of thieves, she learns that the bad guys aren\'t always who they seem. '  ,dateAndTime:'Saturday, February 22, 2020 - 11:00am to 1:00pm',hostedBy:'Jen Guberman', image:'../assets/images/conImages/con6.PNG'}
]
var connection = require('./connection');

var getConnections = function(){
  var connectionsObjectList = [];
  connectionDetails.forEach(function(item){
    var connectionObject = new connection(item.connectionId, item.connection_name, item.connection_category, item.details, item.dateAndTime, item.hostedBy);
    connectionsObjectList.push(connectionObject);
  });
  return connectionsObjectList;
};

var categories = function(){
  var topics = [];
  connectionDetails.forEach(function(item){
    if(!topics.includes(item.connection_category)){
      topics.push(item.connection_category);
    }
  });
  return topics;
};

var getConnection = function(connectionId){
  var connectionObject = '';
  connectionDetails.forEach(function(data){
    if(connectionId == data.connectionId){
      connectionObject = new connection(data.connectionId, data.connection_name, data.connection_category, data.details, data.dateAndTime, data.hostedBy, data.image);
    }
  });
  return connectionObject;
};

var getSavedConnections = function(){
  return savedConnections;
}

module.exports.getConnections = getConnections;
module.exports.categories = categories;
module.exports.getConnection = getConnection;
module.exports.getSavedConnections = getSavedConnections;
